In [3]:
import numpy as np1

In [4]:
a = [4,1,3,7]
a1 = np1.array(a)
print(a1)
print(type(a1))

[4 1 3 7]
<class 'numpy.ndarray'>


In [5]:
print(a1.shape)

(4,)


In [6]:
print(a[2])

3


In [8]:
print(a1.reshape(1,4))
print(a1.reshape(4,1))

[[4 1 3 7]]
[[4]
 [1]
 [3]
 [7]]


In [10]:
a2 = a1.reshape(1,4)
a3 = a1.reshape(4,1)
print(a2.shape)
print(a3.shape)

(1, 4)
(4, 1)


In [11]:
b = [5,7,9]
c = [1,4,7]
d = [12,32,41]
a4 = np1.array([b,c,d])
print(type(a4))
print(a4)
print(a4.shape)

<class 'numpy.ndarray'>
[[ 5  7  9]
 [ 1  4  7]
 [12 32 41]]
(3, 3)


In [12]:
print(a4.reshape(1,9))
print(a4.reshape(9,1))

[[ 5  7  9  1  4  7 12 32 41]]
[[ 5]
 [ 7]
 [ 9]
 [ 1]
 [ 4]
 [ 7]
 [12]
 [32]
 [41]]


In [13]:
print(a4)

[[ 5  7  9]
 [ 1  4  7]
 [12 32 41]]


In [15]:
e=[1,2,3,4,5]
f=[7,8,9,0,1]
g=[1,3,4,5,6]
h=[7,7,2,3,4]
a5=np1.array([e,f,g,h])
print(a5)

[[1 2 3 4 5]
 [7 8 9 0 1]
 [1 3 4 5 6]
 [7 7 2 3 4]]


In [16]:
print(a5[:,:])

[[1 2 3 4 5]
 [7 8 9 0 1]
 [1 3 4 5 6]
 [7 7 2 3 4]]


In [17]:
print(a5[2:,1:3])

[[3 4]
 [7 2]]


In [18]:
print(a5[1:,1:])

[[8 9 0 1]
 [3 4 5 6]
 [7 2 3 4]]


In [19]:
print(a5[1:3,:2])

[[7 8]
 [1 3]]
